# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[project]
name = "student"
version = "0.1.0"
description = "FastAPI-Appserver zur Verwaltung von Studierendendaten"
readme = "README.md"
requires-python = ">=3.15"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.20,<1.0.0"]
build-backend = "uv_build"

[dependency-groups]
lint = [
    "ruff>=0.16.9,<1.0.0",
    "ty>=0.0.84,<1.0.0",
]

[tool.ruff]
preview = true

[tool.ty.environment]
python = "./.venv"
root = ["./src"]

[tool.uv]
required-version = ">=0.12.20"
default-groups = "all"
