# https://docs.sonarqube.org/latest/analysis/analysis-parameters

sonar.projectKey=student
sonar.projectVersion=0.1.0
sonar.python.version=3.14

sonar.scm.disabled=true
# sonar.scm.provider=git

sonar.sources=src/student

sonar.host.url=http://localhost:9000

# Token NICHT hier eintragen, sondern als Umgebungsvariable SONAR_TOKEN setzen:
# SonarQube Token von http://localhost:9000: My Account > Security

sonar.exclusions=\
.venv/**/*,\
.pytest_cache/**/*,\
.ruff_cache/**/*,\
.scannerwork/**/*,\
build/**/*,\
extras/**/*,\
log/*
